name: Clox CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: abel0b/setup-premake@v1
    - name: Generate project
      run: |
        premake5 gmake2
        make config=release
    - name: Run tests
      run: ./tool/bin/run-tests

