name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Dart VM
    - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: ${{ matrix.sdk }}
      - id: install
        name: Install dependencies
        working-directory: ./tool
        run: dart pub get
    - name: Setup premake
      uses: abel0b/setup-premake@v1
    - name: Build makefile
      run: premake5 gmake2
    - name: Make project
      run: make config=release
    - name: Run tests
      run: ./run-tests

