name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: dart-lang/setup-dart@v1.0
    - name: Setup Dart
      working-directory: ./tool
      run: dart pub get
    - uses: abel0b/setup-premake@v1
    - name: Build makefile
      run: premake5 gmake2
    - name: Generate project
      run: make config=release
    - name: Run tests
      run: ./tool/bin/run-tests

